# Generated by Django 5.0.2 on 2024-04-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the brand', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the CPU', max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rank', models.IntegerField(help_text='Enter the rank of the CPU compared to other CPUs')),
                ('num_cores', models.IntegerField(help_text='Enter the number of cores the CPU has')),
                ('core_speed', models.IntegerField(help_text='Enter the speed of the cores in megahertz')),
                ('brand', models.ManyToManyField(help_text='Choose the company that made this CPU', to='parts.brand')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the GPU', max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rank', models.IntegerField(help_text='Enter the rank of the GPU compared to other GPUs')),
                ('memory', models.IntegerField(help_text='Enter the internal memory the GPU has')),
                ('core_speed', models.IntegerField(help_text='Enter the speed of the cores in megahertz')),
                ('brand', models.ManyToManyField(help_text='Choose the company that made this GPU', to='parts.brand')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the RAM', max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rank', models.IntegerField(help_text='Enter the rank of the RAM compared to other RAM sticks')),
                ('DDR_type', models.CharField(choices=[('1', 'DDR1'), ('2', 'DDR2'), ('3', 'DDR3'), ('4', 'DDR4')], help_text='Choose the type of DDR this RAM is', max_length=4)),
                ('amount', models.IntegerField(help_text='Enter the amount of RAM one stick gives in gigabytes')),
                ('brand', models.ManyToManyField(help_text='Choose the company that made this RAM', to='parts.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the storage device', max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rank', models.IntegerField(help_text='Enter the rank of the storage device compared to other storage devices')),
                ('amount_of_space', models.IntegerField(help_text='Enter the amount of space in gigabytes')),
                ('type', models.CharField(choices=[('1', 'HDD'), ('2', 'SSD')], max_length=3)),
                ('brand', models.ManyToManyField(help_text='Choose the company that made this storage device', to='parts.brand')),
            ],
        ),
    ]
